### PR TITLE
Adds new Hello World Starters in a variety of languages.

### PR DESCRIPTION
**Pull request by ispivey**
These were recently added in https://github.com/cloudflare/template-registry/pull/45/files

Screen Shot 2020-07-24 at 2 16 20 PM

### CODE REVIEW

**Comment by adamschwartz** [comment]
I wonder if we should somehow group all of the Hello World examples so that the non-Hello World ones are a bit easier to reach. Now that there are so many Hello World examples at the top, I worry that somebody may stop scrolling thinking that all of the starters are _just_ Hello World.

Could be done as as tabs? Something like this (quickly hacked together):

image

**Comment by davidtsong** [comment]
Yes, tabs would be awesome. Someone also gave me feedback it'd be good to have the multilanguage support for the other code snippets and templates as well.

**Comment by rita3ko** [comment]
Re: language support: 
I was chatting with @davidtsong earlier, it'd be great to have an equivalent of https://wiki.cfops.it/display/EW/Language+Support publicly — especially to call out that there's a difference in the degree to which we "support" different languages. 

I don't think the Examples is the right place to do it, but my ask for the Starters page is to have some sort of "pill" type indicator that specifies that some are "experimental" or "wrangler only" or something.

**Comment by adamschwartz** [comment]
Nice, yea.

Based on this, my quick take is we should add a page under [Platform](https://workers-docs.ruthless.design/reference/platform) called "Languages" (or "Language support", if you prefer). There we could display something akin to that internal table.

Then, on the Starters (and potentially elsewhere), we can do a contextual `<Aside/>` (which discusses e.g. a specific particular lack of support for that language) and also links to the relevant portion of that page.

**Pull request merged**
