### PR TITLE
Add reference-web-crypto

### PR DESCRIPTION
**Pull request by davidtsong**
started initial formatting for web-crypto, the table is pretty broken… I don't know how to fix, needs more copy planning and work

### CODE REVIEW

**Comment by adamschwartz** [comment]
Making this a draft until the content has been rewritten. Add that point please mark it “Ready for review”.

**Comment by ispivey** [comment]
I added some more context, and details of the `SubtleCrypto` interface. You can see it here:

https://workers-docs-webcrypto.ispivey.workers.dev/reference/web-crypto

These APIs are quite complex, and as a result they're pushing the boundaries of the current formatting of method definitions. Wanted to throw this out for feedback – should these methods eventually each have their own page, like we're considering for Streams API classes, and like MDN does for SubtleCrypto methods?

I think these definitely need more "Learning" content, but from a strictly _reference_ perspective most of the content's there now.

**Comment by adamschwartz** [comment]
This looks terrific.

I agree that it it’s pushing the boundaries of the current formatting, but I think we have a pretty straight forward "out" we can use.

For each definition, you can remove the types from the params, and instead describe them inside the definition for that (in this case) method.

```md
<Definitions>

- <Code>encrypt(algorithm<ParamType>object</ParamType>, key<ParamType>CryptoKey</ParamType>,
  data<ParamType>BufferSource</ParamType>)</Code> <Type>Promise&lt;ArrayBuffer></Type>

  - Returns a Promise that fufills with the encrypted data corresponding to the clear text,
    algorithm, and key given as parameters.

</Definitions>
```

```
<Definitions>

- <Code>encrypt(algorithm, key, data)</Code> <Type>Promise&lt;ArrayBuffer></Type>

  - Returns a Promise that fufills with the encrypted data corresponding to the clear text,
    algorithm, and key given as parameters.

    #### Parameters

    - <Code>algorithm<ParamType>object</ParamType></Code> ...
    - <Code>key<ParamType>CryptoKey</ParamType></Code> ...
    - <Code>data<ParamType>BufferSource</ParamType></Code> ...

</Definitions>
```

Result:

**Comment by adamschwartz** [comment]
I just pushed a new component, `TableWrap`, to master. https://github.com/cloudflare/workers-docs-engine/commit/0f62bdd3a186831d9804f200f58a96bf5b208e0d

Then I cherry-picked that into this branch, and then I added the component to the Web Crypto table.

Before and after:

image

image

Wrapping a table with `<TableWrap>` gives you horizontal scrolling and sticky (fixed) left column:

scroll

**Comment by ispivey** [comment]
@adamschwartz the new `TableWrap` component looks great, and that's a perfect suggestion for handling parameters when they get this complex – wish I'd thought of that 😄  I'll go ahead and implement it.

**Comment by adamschwartz** [comment]
I’m so happy to hear that! ☺️ 

After thinking about it a little more and playing with it with a list of definitions (as opposed to just one), I think it may be better to use `__Parameters:__` instead of `#### Parameters`.

```
<Definitions>

- <Code>method(param1, param2, param3)</Code> <Type>Type</Type>

  - Here’s a descriptiong of the method, and why and how it’s used.

    __Parameters:__

    - <Code>param1<ParamType>object</ParamType></Code>
    - <Code>param2<ParamType>string</ParamType></Code>
    - <Code>param3<ParamType>boolean</ParamType></Code>

- <Code>method(param1)</Code> <Type>Type</Type>

  - Here’s a descriptiong of the method, and why and how it’s used.

    __Parameters:__

    - <Code>param1<ParamType>object</ParamType></Code>

- <Code>method(param1, param2)</Code> <Type>Type</Type>

  - Here’s a descriptiong of the method, and why and how it’s used.

    __Parameters:__

    - <Code>param1<ParamType>object</ParamType></Code>
    - <Code>param2<ParamType>string</ParamType></Code>

</Definitions>
```

Looks like this:

image

Small change, but the spacing and logic of it makes a bit more sense to me. Functionally this doesn’t seem quite like an `h4` to me.

**Comment by ispivey** [comment]
I've updated. Last question, though: I included short descriptions of the parameters. I wanted to include links in these, but it appears the sub-list-item contents are not being parsed as Markdown, and thus appear like:

Screen Shot 2020-07-22 at 4 53 40 PM

What do you think the desired approach is here? I like using links because then we don't have to keep doing _deeper_ nesting, and can off-load some of that documentation to others who've already documented this API.

**Comment by adamschwartz** [comment]
For now I worked around this by adding another nested unordered list item:

image

Another reasonable option, if we want to render the details in the same list item as the params, would be to use a [`<Link/>` component for the links](https://workers-docs.ruthless.design/docs-engine/docs-flavored-markdown#links).

**Pull request merged**
